name: lachesis-runtime

services:
  lachesis:
    build:
      context: .
      # This docker compose file is used in production
      target: runtime
      dockerfile: Dockerfile
    image: lachesis-runtime
    container_name: lachesis-runtime
    environment:
      FRONTEND_USERNAME: ${FRONTEND_USERNAME}
      FRONTEND_PASSWORD: ${FRONTEND_PASSWORD}
